title: Lennart Kasserra's Webpage
email: kssrr@tuta.io
description: >- # this means to ignore newlines until "baseurl:"
  I am Lennart, a Master’s student of Data Science with an interest in quantitative Political Science. Here, I mostly write about R programming and software I recommend. Thanks for stopping by!
baseurl: "" # the subpath of your site, e.g. /blog
url: "" # the base hostname & protocol for your site, e.g. http://example.com
github_username:  kssrr

# Build settings
theme: minima
plugins:
  - jekyll-feed

