---
title: "Publications"
---

Schaub, M., Abreu, L., Adeyanju, G. C., Abulfathi, A. A., Bello, M. M., Kasserra, L., Kwaku, A.A., Jalo, M.I., Mahmud, A., Schrage, P. & Jalo, R. I. (2026). Can trust in healthcare be restored after armed violence? Evidence from a randomized field experiment in north-eastern Nigeria. *Social Science & Medicine*, Advance online publication. [Link](https://www.sciencedirect.com/science/article/pii/S0277953626001905)

Schaub, M., Greiner-Filsinger, A., Henic, A., & Kasserra, L. (2025). Exposure to wartime sexual violence in Bosnia and Herzegovina: nationally representative prevalence 30 years after the 1992–1995 war. *Conflict and Health, 19*. [Link](https://link.springer.com/article/10.1186/s13031-025-00741-6)

Schaub, M., Adeyanju, G. C., Abulfathi, A. A., Bello, M. M., Kasserra, L., Kwaku, A. A., Jalo, M.I., Mahmud, A., Schrage, P., Jalo, R.I. & Abreu, L. (2025). Maternal and child healthcare-seeking among victims of violence in armed conflict: a quasi-experimental study in Northeast Nigeria. *BMJ global health, 10*(12). [Link](https://gh.bmj.com/content/10/12/e019494)

